server:
  port: 20124

#logging:
#  level:
#    ROOT: DEBUG    
#    com.lyna.web: DEBUG

spring:
  application:
    name: lyna-spring-boot-thymeleaf
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template: true
    check-template-location: true
    encoding: UTF-8
    mode: HTML
  datasource:
    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/lyna_dev?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate

lyna:
  web:
    pageSize: 10, 20, 50, 100
    limitItems: 10
  ai:
    url: https://jp6jra2fwj.execute-api.ap-northeast-1.amazonaws.com/test/test3
    headers:
      x-api-key: euEcVSr9H0aA2mzwgH62e1N4PuIeUEU99eGodcLy

---
#######################
# Dev environment config
#######################
spring:
  profiles: dev