server:
  port: 20124

spring:
  application:
    name: lyna-spring-boot-thymeleaf
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template: true
    check-template-location: true
    encoding: UTF-8
    mode: HTML
  datasource:
    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.84.20.93:3306/package?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8&useSSL=false
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate

---
#######################
# Dev environment config
#######################
spring:
  profiles: dev